#!/bin/bash

echo "========================================="
echo "   完整的手柄控制底盘启动流程"
echo "========================================="
echo ""
echo "机器人轮子布局确认："
echo "         前方"
echo "          ↑"
echo "    M1         M2"
echo "     \\         /"
echo "      \\       /"
echo "       机器人"
echo "      /       \\"
echo "     /         \\"
echo "    M4         M3"
echo ""
echo "========================================="
echo "启动顺序（需要打开 5 个终端）："
echo "========================================="
echo ""
echo "【终端 1】启动手柄驱动节点"
echo "----------------------------------------"
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 run my_joystick_driver joystick_node"
echo ""
echo "预期输出："
echo "  [INFO] Joystick publisher node initialized"
echo "  [INFO] Auto-detected device: 8BitDo..."
echo ""
echo ""
echo "【终端 2】启动手柄桥接节点"
echo "----------------------------------------"
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "/home/robotics/robocon/new_ws/install/joystick_bridge/bin/joystick_bridge"
echo ""
echo "预期输出："
echo "  [INFO] Joystick bridge node initialized"
echo "  [INFO] Max speed: 100.0 cm/s"
echo ""
echo ""
echo "【终端 3】启动导航节点（逆运动学）"
echo "----------------------------------------"
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 run base_omniwheel_r2_700 local_navigation_node"
echo ""
echo "预期输出："
echo "  [INFO] Local Navigation Node initialized"
echo "  [INFO] Wheel base radius: 327.04 mm"
echo ""
echo ""
echo "【终端 4】启动电机驱动节点（需要 USB-CAN 适配器）"
echo "----------------------------------------"
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 run base_omniwheel_r2_700 damiao_node"
echo ""
echo "预期输出："
echo "  [INFO] Found device at /dev/ttyACM0"
echo "  [INFO] Motor 1 INITIALIZED and ENABLED"
echo "  [INFO] Motor 2 INITIALIZED and ENABLED"
echo "  [INFO] Motor 3 INITIALIZED and ENABLED"
echo "  [INFO] Motor 4 INITIALIZED and ENABLED"
echo ""
echo "⚠️  如果报错 'Device not found'，检查："
echo "   1. USB-CAN 适配器是否连接"
echo "   2. 运行: ls -la /dev/ttyACM*"
echo "   3. 运行: ls -la /dev/serial/by-id/"
echo ""
echo ""
echo "【终端 5】监控电机指令（可选，用于调试）"
echo "----------------------------------------"
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 topic echo /damiao_control"
echo ""
echo ""
echo "========================================="
echo "测试手柄控制："
echo "========================================="
echo ""
echo "1. 确认所有 4 个终端的节点都正常运行"
echo "2. 推动手柄左摇杆 → 控制机器人移动方向和速度"
echo "3. 推动手柄右摇杆 → 控制机器人旋转"
echo ""
echo "左摇杆控制："
echo "  - 向上推：机器人前进"
echo "  - 向下推：机器人后退"
echo "  - 向左推：机器人左移"
echo "  - 向右推：机器人右移"
echo ""
echo "右摇杆控制："
echo "  - 向左推：逆时针旋转"
echo "  - 向右推：顺时针旋转"
echo ""
echo "========================================="
echo "故障排查："
echo "========================================="
echo ""
echo "问题 1：手柄节点报 'No device found'"
echo "  解决：运行 'sudo evtest' 查看设备列表"
echo "       确认手柄已连接并配对（蓝牙/USB）"
echo ""
echo "问题 2：电机节点报 'Device not found'"
echo "  解决：检查 USB-CAN 适配器连接"
echo "       ls -la /dev/serial/by-id/"
echo ""
echo "问题 3：轮子不动但有数据"
echo "  解决：确认终端 4 的 damiao_node 已启动"
echo "       确认电机供电正常"
echo ""
echo "问题 4：轮子运动方向不对"
echo "  解决：记录实际运动方向，反馈给我调整配置"
echo ""
echo "========================================="
