#!/bin/bash
# 完整的重测命令列表

echo "========================================="
echo "   重测完整命令清单"
echo "========================================="
echo ""
echo "你现在已经完成编译，接下来："
echo ""
echo "========================================="
echo "【终端 1】手柄驱动 - 保持运行，不用重启"
echo "========================================="
echo "如果还在运行，就不用管它"
echo "如果停止了，运行："
echo ""
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 run my_joystick_driver joystick_node"
echo ""
echo ""
echo "========================================="
echo "【终端 2】手柄桥接 - 保持运行，不用重启"
echo "========================================="
echo "如果还在运行，就不用管它"
echo "如果停止了，运行："
echo ""
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "/home/robotics/robocon/new_ws/install/joystick_bridge/bin/joystick_bridge"
echo ""
echo ""
echo "========================================="
echo "【终端 3】导航节点 - 必须重启！⚠️"
echo "========================================="
echo "1. 按 Ctrl+C 停止当前节点"
echo "2. 运行以下命令："
echo ""
echo "source install/setup.bash"
echo "ros2 run base_omniwheel_r2_700 local_navigation_node"
echo ""
echo "看到以下信息表示成功："
echo "  [INFO] Local Navigation Node initialized"
echo "  [INFO] Wheel base radius: 327.04 mm"
echo ""
echo ""
echo "========================================="
echo "【终端 4】电机驱动 - 保持运行，不用重启"
echo "========================================="
echo "如果还在运行，就不用管它"
echo "如果停止了，运行："
echo ""
echo "cd /home/robotics/robocon/new_ws"
echo "source install/setup.bash"
echo "ros2 run base_omniwheel_r2_700 damiao_node"
echo ""
echo ""
echo "========================================="
echo "测试步骤："
echo "========================================="
echo ""
echo "1. 推左摇杆向前（远离你的方向）"
echo "2. 观察 4 个轮子："
echo "   - M1 (左前)：往哪转？"
echo "   - M2 (右前)：往哪转？"
echo "   - M3 (右后)：往哪转？"
echo "   - M4 (左后)：动了吗？往哪转？"
echo "3. 观察机器人整体往哪个方向移动"
echo ""
echo "告诉我结果！"
echo ""
echo "========================================="
