#!/bin/bash
# 完整的手柄控制底盘测试系统启动脚本

# 设置工作目录
cd /home/robotics/robocon/new_ws
source install/setup.bash

echo "========================================="
echo "   手柄控制底盘测试系统启动脚本"
echo "========================================="
echo ""
echo "请在不同的终端分别运行以下命令："
echo ""
echo "终端 1 - 手柄驱动："
echo "  cd /home/robotics/robocon/new_ws"
echo "  source install/setup.bash"
echo "  ros2 run my_joystick_driver joystick_node"
echo ""
echo "终端 2 - 手柄桥接节点："
echo "  cd /home/robotics/robocon/new_ws"
echo "  source install/setup.bash"
echo "  /home/robotics/robocon/new_ws/install/joystick_bridge/bin/joystick_bridge"
echo ""
echo "终端 3 - 导航节点："
echo "  cd /home/robotics/robocon/new_ws"
echo "  source install/setup.bash"
echo "  ros2 run base_omniwheel_r2_700 local_navigation_node"
echo ""
echo "终端 4 - 监控电机指令（用于调试，无需连接硬件）："
echo "  cd /home/robotics/robocon/new_ws"
echo "  source install/setup.bash"
echo "  ros2 topic echo /damiao_control"
echo ""
echo "========================================="
echo "如果要启动完整系统（包括电机），还需要："
echo ""
echo "终端 5 - 电机驱动（需要 USB-CAN 适配器）："
echo "  cd /home/robotics/robocon/new_ws"
echo "  source install/setup.bash"
echo "  ros2 run base_omniwheel_r2_700 damiao_node"
echo ""
echo "========================================="
